name: LootBalloon
version: 1.0.6
main: com.xbaimiao.lootballoon.LootBalloon
authors:
  - xbaimiao
depend:
  - MythicMobs
  - ItemsAdder
api-version: "1.13"
folia-supported: true
update-info: "修复音效问题"
